version: '3'
services:
  backend:
    build:
      context: ./backend
      args:
        - CACHEBUST=1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    depends_on:
      - backend